import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import {
  Button,
  Container,
  ListGroup,
} from 'react-bootstrap';

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie API</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className="mt-4">
        <ListGroup>
          <ListGroup.Item>
            <p>
              Get All movies use this endpoint :
              `/api/movies`
            </p>
            <Button>
              <a
                className="text-decoration-none text-white"
                href="/api/movies">
                See
              </a>
            </Button>
          </ListGroup.Item>
          <ListGroup.Item>
            <p>
              Get a movie use this endpoint :
              `/api/movies/idMovie`
            </p>
            <Button>
              <a
                className="text-decoration-none text-white"
                href="/api/movies/6450e068fe038410e3efbf39">
                See
              </a>
            </Button>
          </ListGroup.Item>
        </ListGroup>
      </Container>
    </>
  );
}
